# Generated by Django 3.2.7 on 2021-10-11 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riasec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riasec_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reality', models.IntegerField()),
                ('investigative', models.IntegerField()),
                ('artistic', models.IntegerField()),
                ('social', models.IntegerField()),
                ('enterprising', models.IntegerField()),
                ('conventional', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RIASEC_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('R', 'Reality'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
