# Generated by Django 3.2.7 on 2021-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0002_auto_20211011_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riasec_result',
            name='artistic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='conventional',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='enterprising',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='investigative',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='reality',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='social',
            field=models.FloatField(),
        ),
    ]
