# Generated by Django 3.2.7 on 2021-10-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0003_auto_20211011_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riasec_result',
            options={'verbose_name': 'RIASEC Result', 'verbose_name_plural': 'RIASEC Resuls'},
        ),
        migrations.AlterModelOptions(
            name='riasec_test',
            options={'verbose_name': 'RIASEC Test', 'verbose_name_plural': 'RIASEC Tests'},
        ),
    ]
