# Generated by Django 3.2.7 on 2021-10-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0005_alter_riasec_result_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riasec_result',
            name='artistic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='conventional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='enterprising',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='investigative',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='reality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riasec_result',
            name='social',
            field=models.FloatField(default=0),
        ),
    ]
