# Generated by Django 3.2.7 on 2021-11-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0015_alter_riasec_result_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riasec_result',
            name='reality',
        ),
        migrations.AddField(
            model_name='riasec_result',
            name='realistic',
            field=models.FloatField(default=0),
        ),
    ]
