# Generated by Django 3.2.7 on 2021-11-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0016_auto_20211109_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riasec_test',
            name='category',
            field=models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=100),
        ),
    ]
