# Generated by Django 3.2.7 on 2021-12-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0017_alter_riasec_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='riasec_test',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
